name: "Build, Test and Release Wheel"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      wheel_type:
        description: 'Set wheel type: pre-release or release'
        required: true
        default: 'pre-release'
  # push:  # Temporary trigger for testing (will be removed before merge)
  # merge_group:

jobs:
  build-wheel:
    runs-on: ["in-service"]
    container:
      image: ghcr.io/tenstorrent/pytorch2.0_ttnn/ubuntu-22.04-amd64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
      options: >-
        --rm -v /dev/hugepages-1G:/dev/hugepages-1G --device /dev/tenstorrent
        -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build Python package distribution
        run: |
          python3 -m pip install build
          rm -rf dist/
          python3 -m build
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v4
        with:
          name: torch_ttnn-distributions
          path: dist/

  test-wheel-smoke:
    needs: [build-wheel]
    runs-on: ["in-service"]
    container:
      image: ghcr.io/tenstorrent/pytorch2.0_ttnn/ubuntu-22.04-amd64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
      options: >-
        --rm -v /dev/hugepages-1G:/dev/hugepages-1G --device /dev/tenstorrent
        -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }}
    steps:
      - uses: ./.github/actions/common_wheel_install
      - uses: ./.github/actions/common_smoke_tests

  test-wheel-lowering:
    needs: [build-wheel]
    runs-on: ["in-service"]
    container:
      image: ghcr.io/tenstorrent/pytorch2.0_ttnn/ubuntu-22.04-amd64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
      options: >-
        --rm -v /dev/hugepages-1G:/dev/hugepages-1G --device /dev/tenstorrent
        -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }}
    strategy:
      matrix: # Need to find a way to replace this with a generator
        group: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common_wheel_install
      - uses: ./.github/actions/common_lowering_tests

  test-wheel-model:
    needs: [build-wheel, test-wheel-lowering]
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.wheel_type == 'release'}}
    runs-on: ["in-service"]
    container:
      image: ghcr.io/tenstorrent/pytorch2.0_ttnn/ubuntu-22.04-amd64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
      options: >-
        --rm -v /dev/hugepages-1G:/dev/hugepages-1G --device /dev/tenstorrent
        -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }}
    env:
      pytest_verbosity: 0
      pytest_report_title: "â­ï¸ Model Tests - Group ${{ matrix.group }}"
    strategy:
      matrix: # Need to find a way to replace this with a generator
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: ./.github/actions/common_wheel_install
      - uses: ./.github/actions/common_model_tests
      - name: Upload Metrics Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: wheel-model-tests-metrics-group-${{ matrix.group }}
          path: metrics/

  publish-to-pypi:
    name: >-
      Publish pytorch-ttnn to PyPI
    needs: [build-wheel, test-wheel-lowering, test-wheel-model]
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.wheel_type == 'release'}}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/torch-ttnn
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: torch_ttnn-distributions
        path: dist/
    - name: Publish distribution ðŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
